title: Site

tabs:
  pages:
    columns:

      #posts
      left:
        width: 1/2
        sections:
          posts:
            headline: Posts
            album: pages/aktivitaeten


  style:

  info:







# preset: pages
# unlisted: true
#
# options:
#   delete: false
#   changeTamplate: true
