title: Site

tabs:
  pages:
    columns:

      #posts
      left:
        title: posts
        width: 1/2
        pages:
          type: pages
          create: false
          templates:
            - aktivitaeten
            - library


  style:

  info:







# preset: pages
# unlisted: true
#
# options:
#   delete: false
#   changeTamplate: true
